<?php
/**
 * Privacy Policy Tab Class.
 *
 * This class renders the user options contents in Settings Tab.
 *
 * @package Merryll_Consent_Manager
 * @since   1.0.0
 */

namespace Merryll\Merryll_Consent_Manager\Admin\Tabs;

use Carbon_Fields\Field;

/**
 * Settings Tab Class.
 *
 * @since  1.0.0
 */
class Privacy {

	/**
	 * Accumulates settings fields.
	 *
	 * @access private
	 * @since  1.0.0
	 * @static
	 *
	 * @var array
	 */
	private static $fields;

	/**
	 * Registering the tab contents.
	 *
	 * @since  1.0.0
	 * @access public
	 * @static
	 *
	 * @return array
	 */
	public static function register() {
		self::settings();

		return self::$fields;
	}

	/**
	 * Method to add required fields.
	 *
	 * @since  1.0.0
	 * @access private
	 * @static
	 *
	 * @return static
	 */
	public static function settings() {
		self::$fields[] = Field::make(
			'separator',
			'merryll_settings_policy_html',
			esc_html__( 'Privacy Policy Settings', 'merryll-consent-manager' )
		);

		self::$fields[] = Field::make(
			'select',
			'merryll_privacy_selector',
			esc_html__( 'Privacy Policy Page', 'merryll-consent-manager' )
		)
		->set_classes( 'two-col flex-wrap justify-content-end no-top-border' )
		->set_help_text( esc_html__( 'Please select the Privacy Policy page.', 'merryll-consent-manager' ) )
		->add_options( self::page_list() );

		self::$fields[] = Field::make(
			'text',
			'merryll_privacy_selector_custom',
			esc_html__( 'Privacy Policy Custom URL', 'merryll_consent_manager' )
		)
		->set_classes( 'two-col flex-wrap justify-content-end' )
		->set_help_text( esc_html__( 'Please enter the custom link for Privacy Policy.', 'merryll_consent_manager' ) )
		->set_attribute( 'placeholder', 'https://custom-link.com' )
		->set_conditional_logic(
			array(
				'relation' => 'AND',
				array(
					'field'   => 'merryll_privacy_selector',
					'value'   => 'custom',
					'compare' => '=',
				),
			)
		);

		self::$fields[] = Field::make(
			'text',
			'merryll_privacy_name',
			esc_html__( 'Privacy Policy Name', 'merryll-consent-manager' )
		)
		->set_classes( 'two-col flex-wrap justify-content-end' )
		->set_help_text( esc_html__( 'Please enter the name for Privacy Policy link.', 'merryll_consent_manager' ) )
		->set_default_value( esc_html__( 'Datenschutzerklärung', 'merryll-consent-manager' ) );

		self::$fields[] = Field::make(
			'textarea',
			'merryll_privacy_text',
			esc_html__( 'Privacy Policy Text', 'merryll-consent-manager' )
		)
		->set_classes( 'two-col flex-wrap justify-content-end' )
		->set_help_text( esc_html__( 'Please enter the description for Privacy Policy. Please use {privacyPolicy} with the curly braces to print the autogenerated privacy policy text with link.', 'merryll-consent-manager' ) )
		->set_default_value( esc_html__( 'Informationen dazu finden Sie in unserer {privacyPolicy}.', 'merryll-consent-manager' ) );

		return new static();
	}

	/**
	 * Return the list of pages.
	 *
	 * @since  1.0.0
	 * @access private
	 * @static
	 *
	 * @return static
	 */
	public static function page_list() {
		$pages    = get_pages();
		$pagelist = array(
			'no'     => esc_html__( '--- Select a page ---', 'merryll-consent-manager' ),
			'custom' => esc_html__( '--- Custom External Link ---', 'merryll-consent-manager' ),
		);

		foreach ( $pages as $page ) {
			$pagelist[ $page->ID ] = $page->post_title;
		}

		return $pagelist;
	}
}
